java_library(
    name = "ordinary",
    srcs = [
#        "ReferencesCoreStaticInterface.java",  # If this is uncommented, compilation fails.
        "UsesJava8Features.java",
    ],
    visibility = ["//visibility:public"],
)